### ISSUE TITLE
Version of timm and pytorch

### ISSUE THREAD

**Issue by shenhai911** [liwei109/SepViT#1]
Hello, thanks for your excellent work. I encountered the following problems when using your code, which may be caused by the inconsistency between timm version and pytorch version. My software environment is Python 3.8, Pytorch = 1.10.2, Torchvision = 0.11.3, CUDA = 11.4. Which version of timm is suitable for my software environment, can you give me some suggestions? thank you.
![Selection_159](https://github.com/liwei109/SepViT/assets/26195360/4b0c1f5d-d252-403c-9617-8abc5ac7ec4b)

**Comment by liwei109** [comment]
Please refer to the requirements.txt to create your env, we use timm=0.3.2.
