### ISSUE TITLE
The definition of self.drop_path, self.norm1 and self.norm2

### ISSUE THREAD

**Issue by shenhai911** [liwei109/SepViT#2]
Hello, there are some other questions to ask: 
1. In [the lines 147-148 of sepvit.py](https://github.com/liwei109/SepViT/blob/2b420d3e089c696377fae0c888e1dc0f6bcc564f/classification/sepvit.py#L147), the definitions of self.drop_path, self.norm1 and self.norm2 were not found. Where are they defined?"
![Selection_160](https://github.com/liwei109/SepViT/assets/26195360/984b436e-038c-49e5-8a49-c4ced85c1a19)

2. in [the line 205 of sepvit.py](https://github.com/liwei109/SepViT/blob/2b420d3e089c696377fae0c888e1dc0f6bcc564f/classification/sepvit.py#L205C1-L205C73),  the initial value of 'ws' is [7, 7, 7], while in [the line 231 of sepvit.py](https://github.com/liwei109/SepViT/blob/2b420d3e089c696377fae0c888e1dc0f6bcc564f/classification/sepvit.py#L231C44-L231C55), is the usage of 'ws[k][i]' correct?

![Selection_162](https://github.com/liwei109/SepViT/assets/26195360/b7df2c95-7ed8-4736-8804-980e0b7ad80d)

![Selection_163](https://github.com/liwei109/SepViT/assets/26195360/b4eb257c-db55-4c3d-970f-e0d76decab24)

**Comment by liwei109** [comment]
Q1: self.drop_path, self.norm1 and self.norm2 are in its super class (TimmBlock).
Q2: sorry, there may be some mistakes for initialization but no worries for running, please refer to the model's detailed configs.
